export const PermissionCodes = {
  DASHBOARD_READ: 'DASHBOARD_READ',
  ACTIVIDAD_READ: 'ACTIVIDAD_READ',
  NOTIFICACION_READ: 'NOTIFICACION_READ',
  NOTIFICACION_UPDATE: 'NOTIFICACION_UPDATE',
  RECORDATORIO_READ: 'RECORDATORIO_READ',
  RECORDATORIO_CREATE: 'RECORDATORIO_CREATE',
  RECORDATORIO_UPDATE: 'RECORDATORIO_UPDATE',
  EXPEDIENTE_READ: 'EXPEDIENTE_READ',
  EXPEDIENTE_CREATE: 'EXPEDIENTE_CREATE',
  EXPEDIENTE_UPDATE: 'EXPEDIENTE_UPDATE',
  EXPEDIENTE_DELETE: 'EXPEDIENTE_DELETE',
  EXPEDIENTE_CHANGE_STATE: 'EXPEDIENTE_CHANGE_STATE',
  ACTUACION_CREATE: 'ACTUACION_CREATE',
  ACTUACION_READ: 'ACTUACION_READ',
  ACTUACION_UPDATE: 'ACTUACION_UPDATE',
  ACTUACION_DELETE: 'ACTUACION_DELETE',
  DOCUMENTO_UPLOAD: 'DOCUMENTO_UPLOAD',
  DOCUMENTO_READ: 'DOCUMENTO_READ',
  DOCUMENTO_DOWNLOAD: 'DOCUMENTO_DOWNLOAD',
  AUDIT_READ: 'AUDIT_READ',
  RBAC_MANAGE: 'RBAC_MANAGE',
  USER_MANAGE: 'USER_MANAGE',
} as const;

export type PermissionCode =
  (typeof PermissionCodes)[keyof typeof PermissionCodes];
